#!/usr/bin/env bash
#
# Build the `hc_skins` resource from the client's face-texture skin packs.
#
# These packs are not FiveM resources — each is a single replacement texture
# for one vanilla freemode face (e.g. mp_f_freemode_01^head_diff_019_a_pak.ytd).
# Streaming the texture swaps that face's skin for every character that picks
# it in the creator. This wraps all of them into one resource.
#
# Current mapping (no two skins share a slot, so none overwrite each other):
#   male    face 001  Justin        male    face 017  Raheem
#   female  face 007  Sasha         female  face 008  Asha
#   female  face 009  Kiani         female  face 010  Dalia
#   female  face 011  Leila         female  face 012  Olivia
#   female  face 019  Amber
#
# Usage:  bash scripts/build-skins-resource.sh /root
#         (folder holding "*Skinpack*.zip" and "*Skin*.zip")
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-$ROOT/Files}"
OUT="$ROOT/server-data/resources/[stream]/hc_skins"
TMP="$(mktemp -d "$ROOT/.unpack-XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

shopt -s nullglob nocaseglob
packs=("$SRC"/*skin*.zip)
[[ ${#packs[@]} -gt 0 ]] || { echo "No *skin*.zip archives in $SRC"; exit 1; }

for p in "${packs[@]}"; do
  echo "[......] $(basename "$p")"
  7z x -y -o"$TMP/$(basename "$p" .zip)" "$p" >/dev/null
done
# Skin packs nest one zip per character.
find "$TMP" -iname '*.zip' -print0 | while IFS= read -r -d '' z; do
  7z x -y -o"${z%.*}" "$z" >/dev/null && rm -f "$z"
done

rm -rf "$OUT"; mkdir -p "$OUT/stream"

# Only the FiveM copies: they carry the mp_[mf]_freemode_01^ prefix. The [SP]
# copies are the same texture for singleplayer and must not be streamed.
declare -A seen=()
while IFS= read -r -d '' f; do
  name="$(basename "$f")"
  if [[ -n "${seen[$name]:-}" ]]; then
    echo "COLLISION: $name is supplied by more than one skin — keeping the first." >&2
    continue
  fi
  seen[$name]=1
  cp "$f" "$OUT/stream/$name"
  echo "[OK    ] $name"
done < <(find "$TMP" -type f -iname 'mp_?_freemode_01^head_diff_*.ytd' -print0 | sort -z)

cat > "$OUT/fxmanifest.lua" <<'LUA'
-- Generated by scripts/build-skins-resource.sh — do not edit by hand.
-- Replacement face (skin) textures for freemode peds. See that script for
-- which face slot each skin occupies.
fx_version 'cerulean'
game 'gta5'
name 'hc_skins'
description 'Heartless City custom character skins'
LUA

echo
echo "Built $OUT with ${#seen[@]} skin texture(s). Add 'ensure hc_skins' to server.cfg."
